"""Local data declarations, explicit publication, and lightweight bindings."""

from .errors import (
    AsterStoreError,
    CandidateAbandonedError,
    CandidateStateError,
    HistoryUnavailableError,
    InvalidDeclarationError,
    PublicationConflictError,
    PublicationNotFoundError,
    PublicationRetiredError,
    ReferenceConflictError,
    ReferenceNotFoundError,
    RepositoryNotInitializedError,
    RepositoryUpgradeRequiredError,
    ResourceNotBoundError,
    StoreCorruptionError,
    UnknownMemberError,
    UnknownObjectError,
    UnsupportedCapabilityError,
    UnsupportedPlatformError,
)
from .inspection import CandidateInspection, CandidateResidual, Inspection
from .metadata import (
    CollectionPolicy,
    Dataset,
    ObjectRef,
    PhysicalHistory,
    PreviewIssue,
    Publication,
    Reference,
    ReferenceRecord,
)
from .metadata.capabilities import (
    ByteStability,
    Capabilities,
    HistoryAccess,
    Management,
    RetentionScope,
)
from .metadata.declarations import Declaration
from .metadata.membership import FileSet, Locator, Member, Object
from .metadata.protocol import DeclarationRecord, FixedRetention, ObjectRecord, StoreRecord
from .publishing import Candidate, CandidateStatus
from .publishing.managed import ManagedCandidate, ManagedCandidateStatus
from .reading import Binding
from .registration import RegistrationStatus
from .repository import Repository
from .retention import (
    CandidateCleanupResult,
    CollectionPreview,
    CollectionResult,
    ObjectDecision,
    PublicationDecision,
    RetainedPublication,
    Retention,
)
from .retention.governance import (
    Governance,
    GovernancePreview,
    GovernanceResult,
    ManagedCleanupPreview,
    ManagedCleanupResult,
)

__all__ = [
    "ManagedCleanupPreview",
    "ManagedCleanupResult",
    "FixedRetention",
    "Governance",
    "GovernancePreview",
    "GovernanceResult",
    "ManagedCandidate",
    "ManagedCandidateStatus",
    "DeclarationRecord",
    "ObjectRecord",
    "StoreRecord",
    "RegistrationStatus",
    "ResourceNotBoundError",
    "UnknownMemberError",
    "UnsupportedCapabilityError",
    "ByteStability",
    "Capabilities",
    "HistoryAccess",
    "Management",
    "RetentionScope",
    "Declaration",
    "FileSet",
    "Locator",
    "Member",
    "Object",
    "CandidateAbandonedError",
    "CandidateCleanupResult",
    "CandidateInspection",
    "CandidateResidual",
    "Inspection",
    "PublicationRetiredError",
    "CollectionResult",
    "CollectionPolicy",
    "CollectionPreview",
    "ObjectDecision",
    "PublicationDecision",
    "PreviewIssue",
    "ReferenceRecord",
    "RetainedPublication",
    "Retention",
    "ReferenceConflictError",
    "ReferenceNotFoundError",
    "RepositoryUpgradeRequiredError",
    "AsterStoreError",
    "Binding",
    "Candidate",
    "CandidateStatus",
    "CandidateStateError",
    "Dataset",
    "InvalidDeclarationError",
    "HistoryUnavailableError",
    "ObjectRef",
    "PhysicalHistory",
    "Publication",
    "PublicationConflictError",
    "PublicationNotFoundError",
    "Reference",
    "Repository",
    "RepositoryNotInitializedError",
    "StoreCorruptionError",
    "UnknownObjectError",
    "UnsupportedPlatformError",
]
